version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - C:\Users\wallace.costa\backup:/var/lib/postgresql/data

      